# Generated by Django 4.2.2 on 2023-06-12 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samp_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientmodel',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='clientmodel',
            name='on_trial',
        ),
        migrations.RemoveField(
            model_name='clientmodel',
            name='paid_until',
        ),
    ]
